DROP TABLE IF EXISTS `977r`.`tbl_ccf_acap_ext`;
CREATE TABLE  `977r`.`tbl_ccf_acap_ext` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `TIPO_FACTURACION` varchar(1) CHARACTER SET latin1 DEFAULT NULL,
  `fichero` varchar(12) CHARACTER SET latin1 NOT NULL,
  
  `CampoClave` varchar(8) CHARACTER SET latin1 NOT NULL,
  
  `FECHA_FACTURA` varchar(8) CHARACTER SET latin1 NOT NULL,
  `CIF_CLIENTE_Clave` varchar(18) CHARACTER SET latin1 NOT NULL,
  `Acuerdo` varchar(18) CHARACTER SET latin1 NOT NULL,
  
  `CODIGO_REGISTRO_EXT` varchar(8) CHARACTER SET latin1 NOT NULL,
  `CODIGO_REGISTRO` int(11) DEFAULT '0',
  `SECUENCIAL` int(11) DEFAULT '0',
  
  `CLIENTE` varchar(8) CHARACTER SET latin1 DEFAULT NULL,
  
  `Tipo_Doc` varchar(1) CHARACTER SET latin1 DEFAULT NULL,
  `CIF` varchar(9) CHARACTER SET latin1 DEFAULT NULL,
  `NOMBRE_CLIENTE` varchar(70) CHARACTER SET latin1 DEFAULT NULL,
  
  `TIPO_DOC_REASIGNADO` varchar(1) DEFAULT 'L',
  `CIF_REASIGNADO` varchar(9) CHARACTER SET latin1 DEFAULT NULL,
  `NOMBRE_CLIENTE_REASIGNADO` varchar(70) CHARACTER SET latin1 DEFAULT NULL,
  
  `AGRUPACION_FACTURABLE` varchar(12) CHARACTER SET latin1 DEFAULT NULL,
  `GRUPO_DE_GASTO` varchar(12) CHARACTER SET latin1 DEFAULT NULL,
  
  `TIPO_DE_SERVICIO` varchar(12) CHARACTER SET latin1 DEFAULT NULL,
  `DESC_TIPO_DE_SERVICIO` varchar(180) CHARACTER SET latin1 DEFAULT NULL,
  
  `MULTICONEXION` varchar(20) CHARACTER SET latin1 DEFAULT NULL,
  `NUMERO_COMERCIAL` varchar(20) CHARACTER SET latin1 DEFAULT NULL,
  `NUMERO_COMERCIAL_ASOCIADO` varchar(20) CHARACTER SET latin1 DEFAULT NULL,
  
  `LONGITUD_REGISTRO` int(11) DEFAULT '0',
  `CODIGO_CONCEPTO` varchar(2) CHARACTER SET latin1 DEFAULT NULL,
  `DESC_CODIGO_CONCEPTO` varchar(180) CHARACTER SET latin1 DEFAULT NULL,
  
  `IMPORTE_TOTAL_EQUIPO` double(15,4) DEFAULT '0.0000',
  `IMPORTE_ESTANDAR_PRODUCTO` double(15,4) DEFAULT '0.0000',
  `IMPORTE_DISTANCIA` double(15,4) DEFAULT '0.0000',
  `IMPORTE_UNITARIO` double(15,4) DEFAULT '0.0000',
  
  `DESCRIPCION_PERIODO_1` varchar(1) CHARACTER SET latin1 DEFAULT NULL,
  `UNIDADES_PERIODO_1` int(11) DEFAULT '0',
  
  `DESCRIPCION_PERIODO_2` varchar(1) CHARACTER SET latin1 DEFAULT NULL,
  `UNIDADES_PERIODO_2` int(11) DEFAULT '0',
  
  `TIPO_VALORACION` varchar(1) CHARACTER SET latin1 DEFAULT NULL,
  `DESC_VALORACION` varchar(180) CHARACTER SET latin1 DEFAULT NULL,
  
  `FECHA_INICIO_PERIODO` date DEFAULT NULL,
  `FECHA_FIN_PERIODO` date DEFAULT NULL,
  
  `CONCEPTO_FACTURABLE` varchar(14) CHARACTER SET latin1 DEFAULT NULL,
  `DESC_CONCEPTO_FACTURABLE` varchar(180) CHARACTER SET latin1 DEFAULT NULL,
  `CODIGO_PAQUETE` varchar(14) CHARACTER SET latin1 DEFAULT NULL,
  `CODIGO_PERSONALIZACION` varchar(14) CHARACTER SET latin1 DEFAULT NULL,
  `UNIDADES` int(11) DEFAULT '0',
  `NIVEL_IMPOSITIVO` varchar(1) CHARACTER SET latin1 DEFAULT NULL,
  `DESC_NIVEL_IMPOSITIVO` varchar(180) CHARACTER SET latin1 DEFAULT NULL,
  `TIPO_IMPOSITIVO` double(5,2) DEFAULT '0.00',
  
  
  `CODIGO_DESCUENTO_1` varchar(14) CHARACTER SET latin1 DEFAULT NULL,
  `DESC_CODIGO_DESCUENTO_1` varchar(180) CHARACTER SET latin1 DEFAULT NULL,
  `CODIGO_PERSONALIZADO_1` varchar(14) CHARACTER SET latin1 DEFAULT NULL,
  `IMPORTE_DESCUENTO_1` double(15,4) DEFAULT '0.0000',
  
  `CODIGO_DESCUENTO_2` varchar(14) CHARACTER SET latin1 DEFAULT NULL,
  `DESC_CODIGO_DESCUENTO_2` varchar(180) CHARACTER SET latin1 DEFAULT NULL,
  `CODIGO_PERSONALIZADO_2` varchar(14) CHARACTER SET latin1 DEFAULT NULL,
  `IMPORTE_DESCUENTO_2` double(15,4) DEFAULT '0.0000',
  
  `CODIGO_DESCUENTO_3` varchar(14) CHARACTER SET latin1 DEFAULT NULL,
  `DESC_CODIGO_DESCUENTO_3` varchar(180) CHARACTER SET latin1 DEFAULT NULL,
  `CODIGO_PERSONALIZADO_3` varchar(14) CHARACTER SET latin1 DEFAULT NULL,
  `IMPORTE_DESCUENTO_3` double(15,4) DEFAULT '0.0000',
  
  `precio_especial` varchar(10) DEFAULT 'NO',
  `importe_acuerdo` double(15,4) DEFAULT '0.0000',
  `tipo_precio_especial` varchar(45) DEFAULT 'PPI',
  `importe_BOE` double(15,4) DEFAULT '0.0000',
  `descuentos_BOE` double(21,4) DEFAULT NULL,
  `BOE_con_descuentos` double(21,4) DEFAULT NULL,
  `precio_acuerdo` double(25,8) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_fichero` (`fichero`),
  KEY `idx_acuerdo` (`Acuerdo`),
  KEY `idx_cif` (`CIF`),
  KEY `idx_cif_reasignado` (`CIF_REASIGNADO`),
  KEY `idx_tipo_de_servicio` (`TIPO_DE_SERVICIO`),
  KEY `idx_multiconexion` (`MULTICONEXION`),
  KEY `idx_numero_comercial` (`NUMERO_COMERCIAL`),
  KEY `idx_concepto_facturable` (`CONCEPTO_FACTURABLE`)
) ENGINE=MyISAM AUTO_INCREMENT=646831 DEFAULT CHARSET=utf8;