DROP VIEW IF EXISTS v100000;
CREATE VIEW v100000 AS
select 
	t1.fichero AS fichero,
	t1.CampoClave AS CampoClave,
	t1.FECHA_FACTURA AS FECHA_FACTURA,
	t1.CIF_CLIENTE_Clave AS CIF_CLIENTE_Clave,
	t1.ACUERDO AS Acuerdo,
	
	t1.CODIGO_REGISTRO_EXT AS CODIGO_REGISTRO_EXT,
	t1.CODIGO_REGISTRO AS CODIGO_REGISTRO,
	t1.SECUENCIAL AS SECUENCIAL,
	t1.CLIENTE AS CLIENTE,
	t1.AGRUPACION_FACTURABLE AS AGRUPACION_FACTURABLE,
	t1.GRUPO_DE_GASTO AS GRUPO_DE_GASTO,
	t1.TIPO_DE_SERVICIO AS TIPO_DE_SERVICIO,
	t1.MULTICONEXION AS MULTICONEXION,
	t1.NUMERO_COMERCIAL AS NUMERO_COMERCIAL,
	t1.NUMERO_COMERCIAL_ASOCIADO AS NUMERO_COMERCIAL_ASOCIADO,
	t1.LONGITUD_REGISTRO AS LONGITUD_REGISTRO,
	t1.CODIGO_CONTROL AS CODIGO_CONTROL,
	t1.CIF_SUPRACLIENTE AS CIF_SUPRACLIENTE,
	t1.NOMBRE_SUPRACLIENTE AS NOMBRE_SUPRACLIENTE,
	t1.IMPORTE_A_PAGAR AS IMPORTE_A_PAGAR,
	t1.TOTAL_FACTURADO AS TOTAL_FACTURADO,
	t1.IMPORTE_PROMOCIONES AS IMPORTE_PROMOCIONES,
	t1.IMPORTE_IMPUESTOS AS IMPORTE_IMPUESTOS,
	t1.IMPORTE_REDONDEO AS IMPORTE_REDONDEO,

	t2.CODIGO_CONCEPTO AS CODIGO_CONCEPTO,
	t2.IMPORTE_CONCEPTO AS IMPORTE_CONCEPTO,
	t2.IMPORTE_DESCUENTO AS IMPORTE_DESCUENTO 

from  t100000_1 t1 
	left join t100000_2 t2 
		on   t1.CampoClave = t2.CampoClave  
		and  t1.fichero = t2.fichero     
		and  t1.ACUERDO = t2.ACUERDO  
		and  t1.FECHA_FACTURA = t2.FECHA_FACTURA    
;